### ISSUE TITLE
World Boss Timer not showing.

### ISSUE THREAD

**Issue by BalkirCalmune** [juddisjudd/d4-timers#2]
When I first downloaded this it had just the Helltide and World Boss timers, but with the addition of the Legion timer, the World Boss timer no longer displays on the overlay.

**Comment by juddisjudd** [comment]
> When I first downloaded this it had just the Helltide and World Boss timers, but with the addition of the Legion timer, the World Boss timer no longer displays on the overlay.

Are you using release version 2 or OBS browser source version?

It's definitively showing for bother versions:
![](https://i.imgur.com/afgi6Hg.png)

**Comment by BalkirCalmune** [comment]
Aparently I didn't have the 2.0 version as I grabbed the download from the link in the "How to use" section and that didn't give me the lastest version.

**Comment by juddisjudd** [comment]
I've updated that link, thank you!
